name: Generate Salish Sea Report

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes
  workflow_dispatch:  # lets you trigger it manually from the GitHub UI

jobs:
  run-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run NOAA buoy script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python Salish_Alerts.py

      - name: Commit and push results
        run: |
          git config user.name "GavinScoville"
          git config user.email "gavin.scoville@gmail.com"
          git add -A
          git commit -m "Auto-update buoy report [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/GavinScoville/Buoy_Proj.git HEAD:main




